config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	get 'sessions/new'
	root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, :ships, :jobs, :ship_jobs
	get    '/login',   to: 'sessions#new'
  	post   '/login',   to: 'sessions#create'
  	delete '/logout',  to: 'sessions#destroy'

end

app/models/job.rb
class Job < ApplicationRecord
	has_many :ship_jobs
	has_many :ships, through: :ship_jobs
	

	validates :destination, presence: true,
                    length: { minimum: 50 }
    validates :name, uniqueness: true
    validates_numericality_of :cost, greater_than: 1000

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
		def index
			

		end

		def new 
			Job.new

		end

		def show
			@job = Job.find(params[:id])
			@contains = @job.containersNeeded
			@total = 0 
			@final = 0
			


		end

		def edit

			@job = Job.find(params[:id])


			
		end

		def update
    	 # @job = Job.find(params[:id])
 

    if @job.update(job_params)
      		redirect_to @job
    else
      		render 'show'
    end

  end

		def destroy
		   # @job = Job.find(params[:id])
		   @job.destroy
		 
		  		redirect_to jobs_path
		end

		def create
				Job.create(description: params[:job][:description], name: params[:job][:name], origin: params[:job][:origin], destination: params[:job][:destination], cost: params[:job][:cost], containersNeeded: params[:job][:containersNeeded], user_id: current_user.id)

				redirect_to jobs_path

  		end
		

		
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/Jobs/edit.html.erb
<h1>Editing Jobs</h1>

<%= form_for(@job) do |f| %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </p>

  <p>
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </p>

  <p>
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </p>

  <p>
    <%= f.label :containersNeeded %><br>
    <%= f.text_field :containersNeeded %>
  </p>

   <p>
    <%= f.submit 'Edit Jobs'%>
  </p>

<% end %>

<%= link_to 'Job Lists', jobs_path %> | <%= link_to 'Delete Job', @job, method: :delete, data: { confirm: 'Are you sure want to delete this job?' } %>

app/views/Jobs/index.html.erb
<h1>Your Jobs | <%=link_to "Add Job", new_job_path%></h1>

 
    <% current_user.jobs.each do |t| %>
    <!--finds out the amount of containers needed based on how many are already assigned -->
      <%@contains = 0 %>
      <% t.ship_jobs.each do |n| %>
        <% @ships = Ship.where(id: n.ship_id).first%>
        <%@contains = t.containersNeeded - @ships.containers%>
        <%puts @contains%>
      <%end%>
      <div class='col-lg-2'>
        <h1><%= link_to t.name, t  %></h1>
        <h6>Origin: <%= t.origin %></h6>
        <h6>Destination: <%= t.destination %></h6>
      </div>
    <% end %>
 

app/views/Jobs/new.html.erb
<h1>New Jobs</h1>

<%= form_for :job, url: jobs_path do |f| %>

	<p>
		<%= f.label :origin %><br>
		<%= f.select :origin, ['Sydney', 'Boston', 'Beijing', 'New York'], include_blank: true %><br>
	</p>
	<p>
		<%= f.label :destination %><br>
		<%= f.select :destination, ['Sydney', 'Boston', 'Beijing', 'New York'], include_blank: true %><br>
	</p>
	
		<p>
		<%= f.label :cost %><br>
		<%= f.number_field :cost %><br>
	</p>

		<p>
		<%= f.label :Containers_Needed_for_Job %><br>
		<%= f.number_field :containersNeeded %><br>
	</p>

		<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %><br>
	</p>

	<p>
	<%= f.submit method: :new, data: { confirm: 'Are you sure want add this ship?' } %>
	</p>

<% end %>

app/views/Jobs/show.html.erb
<%@job = Job.find(params[:id])%>
     <% @job.ship_jobs.each do |n| %>
    <%  @ships = Ship.where(id: n.ship_id).first %>
       <% @total += @ships.containers %>
       <% puts @contains %>
     <% end %>
     <% @final = @contains - @total %>



<div class='col-lg-5'>

  <h1><%=@job.name%></h1>
  <h5><%=@job.origin%></h5>
  <h5><%=@job.destination%></h5>
  <% if @final <= 0 %>
    <h5>Containers Needed: 0</h5>
  <% else %>
  <h5>Containers Needed: <%=@final%></h5>
  <%end%>
  <h5>$<%=@job.cost%></h5>
  <h5><%=@job.description%></h5>
  <h6><%= link_to 'Edit', edit_job_path(@job.id) %> </h6> 
  <h6><%= link_to 'Delete', @job, method: :delete, data: { confirm: 'Are you sure want to delete this job?' } %> </h6>
      <%if @contains <= 0 %>
          <h6>No More Containers Needed</h6>
      <%else%>
          <h6><%= link_to 'Add Ship to Job', new_ship_job_path%></h6>
      <%end%>
</div>
<div class = 'col-lg-5'>
  <h1>Ships Assigned Ships:</h1>
  <% @job.ship_jobs.each do |n| %>
    <%  @ships = Ship.where(id: n.ship_id).first %>
    <h4><%=@ships.name%></h4>
  <%end%>
</div>

