config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	get 'sessions/new'
	root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, :ships, :jobs, :ship_jobs
	get    '/login',   to: 'sessions#new'
  	post   '/login',   to: 'sessions#create'
  	delete '/logout',  to: 'sessions#destroy'

end

app/models/ship.rb
class Ship < ApplicationRecord
	has_many :ship_jobs
	has_many :jobs, through: :ship_jobs
	mount_uploader :avatar, AvatarUploader
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController


	def index
		  @ship = Ship.all

		end

		def new 
			 @ship = Ship.new

		end

		def show
				# @ship = Ship.find(params[:id])

		end

		def edit
				# @ship = Ship.find(params[:id])
			
		end

		def update
			  @ship= Ship.find(params[:id])
			 
			  if @ship.update(ship_params)
			    redirect_to @ship
			  else
			    render 'show'
 		 end
	end

			
		def destroy
			  @ship = Ship.find(params[:id])
			  @ship.destroy
			 
			  redirect_to ships_path
		end

		def create
				# @ship = Ship.new(ship_params)
				Ship.create(name: params[:ship][:name], containers: params[:ship][:containers], location: params[:ship][:location], avatar: params[:ship][:avatar], user_id: current_user.id)
			# 	if @ship.save
			# 	redirect_to @ship
			# else
   #  			render 'new'
  	# 	end
  		redirect_to ships_path
		end

		def ship_params 
				params.require(:ship).permit(:name, :containers, :location, :user_id)

	end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/edit.html.erb
<h1>Edit Ships</h1>
<% @ship = Ship.find(params[:id])%>
<%= form_for(@ship) do |f| %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :containers %><br>
    <%= f.text_field :containers %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </p>

   <p>
    <%= f.submit 'Edit Ships'%>
  </p>
 

<% end %>
 
<%= link_to 'Ship Lists', ships_path %> | <%= link_to 'Delete Ship', @ship, method: :delete, data: { confirm: 'Are you want to delete this ship sure?' } %>

app/views/ships/index.html.erb
<h1>Your Ships <%=link_to "Add Ship", new_ship_path%></h1>




    <% current_user.ships.each do |ship| %>
      <div class='col-lg-2 indships'>
        <%=image_tag ship.avatar_url(:thumb)%>
        <h3><%= link_to ship.name, ship %></h3>
        <h6>Containers: <%= ship.containers %></h6>
        <h6>Location: <%= ship.location %></h6>
        
        <br>
        <%= link_to 'Edit', edit_ship_path(ship.id) %> | 
        <%= link_to 'Delete', ship, method: :delete, data: { confirm: 'Are you sure want to delete this ship?' } %>
      </div>
    <% end %>

app/views/ships/new.html.erb
<h1>New Ships</h1>

	<%= form_for :ship, url: ships_path do |f| %>


		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %><br>
		</p>
		<p>
			<%=f.label :Maximum_Containers%><br>
			<%=f.number_field :containers%><br>
		<p>
			<%= f.label :location %><br>
			<%= f.select :location,["New York", "Miami", "Beijing", "Sydney"] %><br>
		</p>
		<p>

			<%= f.label :Image%><br>
			<%= f.file_field :avatar%>
		</p>
		<p>
			<%= f.submit method: :new, data: { confirm: 'Are you sure want add this ship?' } %>

		</p>

<% end %>

app/views/ships/show.html.erb
<%@ship = Ship.find(params[:id])%>
<%puts @ship %>
<p>
  <strong>Name:</strong>
  <%= @ship.name %>
</p>

<p>
  
 
<%= link_to 'Delete Ship', method: :delete, data: { confirm: 'Are you sure want to delete this ship?' } %>