config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	get 'sessions/new'
	root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, :ships, :jobs, :ship_jobs
	get    '/login',   to: 'sessions#new'
  	post   '/login',   to: 'sessions#create'
  	delete '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :ship_jobs
	has_many :ships, through: :ship_jobs
	

	validates :destination, presence: true,
                    length: { minimum: 50 }
    validates :name, uniqueness: true
    validates_numericality_of :cost, greater_than: 1000

end

app/models/ship.rb
class Ship < ApplicationRecord
	has_many :ship_jobs
	has_many :jobs, through: :ship_jobs
	mount_uploader :avatar, AvatarUploader
end

app/models/ship_job.rb
class ShipJob < ApplicationRecord
	belongs_to :ship 
	belongs_to :job
	validates :job_id, :uniqueness => {:scope => :ship_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :ships
	has_many :jobs

	validates :name, uniqueness: true
end

app/controllers/[scope]/confirmations_controller.rb
class [scope]::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/[scope]/passwords_controller.rb
class [scope]::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/[scope]/sessions_controller.rb
class [scope]::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/[scope]/unlocks_controller.rb
class [scope]::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def after_sign_in_path_for(resource)
  session[:id] = current_user.id
  user_path(resource)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
		def index
			

		end

		def new 
			Job.new

		end

		def show
			@job = Job.find(params[:id])
			@contains = @job.containersNeeded
			@total = 0 
			@final = 0
			


		end

		def edit

			@job = Job.find(params[:id])


			
		end

		def update
    	 # @job = Job.find(params[:id])
 

    if @job.update(job_params)
      		redirect_to @job
    else
      		render 'show'
    end

  end

		def destroy
		   # @job = Job.find(params[:id])
		   @job.destroy
		 
		  		redirect_to jobs_path
		end

		def create
				Job.create(description: params[:job][:description], name: params[:job][:name], origin: params[:job][:origin], destination: params[:job][:destination], cost: params[:job][:cost], containersNeeded: params[:job][:containersNeeded], user_id: current_user.id)

				redirect_to jobs_path

  		end
		

		
end

app/controllers/ship_jobs_controller.rb
class ShipJobsController < ApplicationController
	def index

		end

		def new 

		end

		def show
				# @shipjob = Shipjob.find(params[:id])

		end

		def edit
			
		end

		def update
			
		end

		def destroy
			
		end

		def create
		@shipjob = ShipJob.create(ship_id: params[:ship_job][:ship_id], job_id: params[:ship_job][:job_id])
				

				if @shipjob.save
					redirect_to jobs_path
				else
					flash[:notice]="Ship has already been added to this job."
					render :new
				end
				
		end

		
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController


	def index
		  @ship = Ship.all

		end

		def new 
			 @ship = Ship.new

		end

		def show
				# @ship = Ship.find(params[:id])

		end

		def edit
				# @ship = Ship.find(params[:id])
			
		end

		def update
			  @ship= Ship.find(params[:id])
			 
			  if @ship.update(ship_params)
			    redirect_to @ship
			  else
			    render 'show'
 		 end
	end

			
		def destroy
			  @ship = Ship.find(params[:id])
			  @ship.destroy
			 
			  redirect_to ships_path
		end

		def create
				# @ship = Ship.new(ship_params)
				Ship.create(name: params[:ship][:name], containers: params[:ship][:containers], location: params[:ship][:location], avatar: params[:ship][:avatar], user_id: current_user.id)
			# 	if @ship.save
			# 	redirect_to @ship
			# else
   #  			render 'new'
  	# 	end
  		redirect_to ships_path
		end

		def ship_params 
				params.require(:ship).permit(:name, :containers, :location, :user_id)

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/ship_jobs_helper.rb
module ShipJobsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/create_ship_jobs/new.html.erb
<h1>new Jobs</h1>

<%= form_for :job, url: jobs_path do |f| %>
			<% if @job.error.any? %>
				<% @job.error.full_messages.each do |msg| %>
					<div class="alert alert-danger"><%= msg %></div>
			<% end %>
	<p>
		<%= f.label :ship_id %><br>
		<%= f.text_field :ship_id  %><br>
	</p>
	<p>
		<%= f.label :job_id %><br>
		<%= f.text_field :job_id %><br>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-lg-2" id='nav'>
      <% if user_signed_in? %>
		<div class="row-offcanvas row-offcanvas-left">
		  <div id="sidebar" class="sidebar-offcanvas">
		      <div class="col-md-12">
		        <h3>Ship It</h3>
		        <ul class="nav nav-pills nav-stacked">
		          <li class="<%= 'active' if current_page?(user_path(current_user)) %>"><%= link_to "Dashboard", user_path(current_user)%></li>
		          <li class="<%= 'active' if current_page?(url_for(:ships)) %>"><%= link_to "Ships", url_for(:ships)%></li>
		          <li class="<%= 'active' if current_page?(job_path(current_user)) %>"><%= link_to "Jobs", url_for(:jobs)%></li>
		          <li ><%=link_to "Logout", destroy_user_session_path, method: :delete%></li> 
		        </ul>
		      </div>
                <% flash.each do |name, msg| %>
          <div data-alert id="flashes">
              <%= content_tag :div, msg, id: "flash_#{name}" %>
              <a href="#" class="close">&times;</a>
          </div>
<% end %>

		  </div>
		<%end%>
    </div>
    </div>
    <div class="col-sm-9 col-lg-10">
     <%= yield %>
    </div>
  </div>
</div>
    
  </body>
</html>